### ISSUE TITLE
Deploying into region which differs from target region? 

### ISSUE THREAD

**Issue by pat-s** [amancevice/terraform-aws-custom-ecr-domain#1]
I am currently facing the issue that `apigatewayv2` is not available in a certain region for which I would like to use your approach for (which is very much appreciated!).

Hence I wondered if certain components could technically be deployed to another region and implement a redirect for a different region?

This would probably require splitting certain region-based variables into the region for deployment and the region for the ECR redirect. DO you think that this could work from a technical point of view?

**Comment by amancevice** [comment]
great feature request—let me see what I can do

**Comment by amancevice** [comment]
just pushed v1.0.0 with an optional `ecr_registry` variable where you can provide your own registry in a different region. Let me know if this works for you

**Comment by amancevice** [comment]
d'oh!

**Comment by amancevice** [comment]
ok @pat-s I believe I have corrected all the typos. incredible that I was able to make them just so that it passed CI/CD tests. `v1.0.1` out now

**Comment by pat-s** [comment]
FYI: Worked perfectly!
